# Generated by Django 3.0.7 on 2020-06-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('added_date', models.DateField()),
            ],
        ),
    ]
