# Generated by Django 3.0.7 on 2020-06-30 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='added_date',
            new_name='created',
        ),
    ]
