# Generated by Django 3.0.7 on 2020-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200630_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
