# Generated by Django 3.0.7 on 2020-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200630_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='coverpicture',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
