# Generated by Django 3.0.7 on 2020-06-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_books_coverpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
